jenkinsci/git-forensics-plugin

- src/main/java/io/jenkins/plugins/git/forensics/blame/GitBlamer.java
- src/test/java/io/jenkins/plugins/git/forensics/blame/GitBlamerITest.java
- src/test/java/io/jenkins/plugins/git/forensics/blame/GitBlamerTest.java
See [JENKINS-59252](https://issues.jenkins-ci.org/browse/JENKINS-59252).
Some tools do not report line numbers for warnings, some other tools use line number 0 to indicate that the warning is  for the whole file. In those cases, the blame information should be taken from the last commit for the affected file.
> [JENKINS-59252] Use last committer of the affected file of warning lineNumber == 0.

- pom.xml
- src/main/java/io/jenkins/plugins/forensics/git/blame/GitBlamer.java
- src/test/java/io/jenkins/plugins/forensics/git/blame/GitBlamerTest.java
See [JENKINS-60014](https://issues.jenkins-ci.org/browse/JENKINS-60014).
Introduce the time of a commit to the blame. This enables the user to see not only who made a change, but also when the change was made.
This implements the changes from the forensics-api-plugin (https://github.com/jenkinsci/forensics-api-plugin/pull/47). As long as the PR there is not merged and the new version of the maven package is not released, the present pull request will not build.
> [JENKINS-60014] Add the time of a commit to the blame.

- plugin/src/test/java/io/jenkins/plugins/forensics/git/miner/GitMinerStepITest.java
- skip.sh
HTML unit integration tests are too slow and flaky. Since we already have a UI test for the table it makes sense to simplify the integration test.
> Replace HTML unit test with a model based table test

- Jenkinsfile
Updated to follow what is in the buildPlugin.groovy from the global pipeline library.
Is there a reason that you aren't using buildPlugin() directly? Maybe something we could implement in the global library so we can keep a single source of buildPlugin?
> Remove forceUseAci like update to global library

- plugin/pom.xml
- plugin/src/main/java/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorder.java
- plugin/src/main/resources/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorder/config.jelly
- plugin/src/test/java/io/jenkins/plugins/forensics/git/ArchitectureTest.java
Downstream PR of jenkinsci/plugin-util-api-plugin#66. 
Use `@POST` for field validation. For details see https://www.jenkins.io/doc/developer/security/form-validation/.
> Use @POST for form field validation

- plugin/src/main/java/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorder.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/reference/package-info.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorderITest.java
- ui-tests/src/test/java/io/jenkins/plugins/forensics/ForensicsPluginUiTest.java
Fix NPE if reference job does not yet have a `GitCommitsRecord` action attached.
See https://issues.jenkins-ci.org/browse/JENKINS-64545.
> [JENKINS-64545] Fix NPE 

- plugin/pom.xml
- plugin/src/main/java/io/jenkins/plugins/forensics/git/reference/GitCheckoutListener.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorder.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/util/GitRepositoryValidator.java
- plugin/src/main/resources/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorder/config.jelly
- plugin/src/main/resources/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorder/config.properties
- plugin/src/test/java/io/jenkins/plugins/forensics/git/miner/GitMinerStepITest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/reference/GitCheckoutListenerITest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorderITest.java
- ui-tests/src/test/java/io/jenkins/plugins/forensics/ForensicsPluginUiTest.java
Some jobs are using multiple SCM repositories: one for the code, one for the pipeline library, etc. We need a way to select the correct repository for all features of the forensics API. See also [JENKINS-64578](https://issues.jenkins.io/browse/JENKINS-64578).
> [JENKINS-64578] Support multiple SCM repositories per job

- plugin/pom.xml
- plugin/src/main/java/io/jenkins/plugins/forensics/git/reference/GitCheckoutListener.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/reference/GitCheckoutListenerITest.java
Otherwise we get the same repository twice, see example build https://ci.jenkins.io/job/Plugins/job/analysis-model/job/master/1095/
> Do not add a new action if already attached by a parallel step

- plugin/pom.xml
- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/CommitStatisticsStep.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/GitRepositoryMiner.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/MergeBaseSelector.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/RepositoryStatisticsCallback.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/util/GitCommitTextDecorator.java
- plugin/src/main/webapp/icons/LICENSE.txt
- plugin/src/test/java/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorderITest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/util/GitITest.java
- plugin/src/test/resources/design.puml
- ui-tests/src/test/java/io/jenkins/plugins/forensics/ForensicsPluginUiTest.java
Currently the repository miner creates statistics for the whole repository only. In order to compute delta statistics for pull requests (and branches) an additional miner step has been added.
Downstream PR of jenkinsci/forensics-api-plugin#293
> Add delta forensics for PR and branch builds

- plugin/pom.xml
Bump credentials from 2.4.1 to 2.5 to resolve issue with #306 and the other dependencies.
> Bump credentials from 2.4.1 to 2.5

- plugin/pom.xml
- plugin/src/main/java/io/jenkins/plugins/forensics/git/blame/package-info.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/CommitAnalyzer.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/CommitCollector.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/CommitStatisticsStep.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/GitRepositoryMiner.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/MergeBaseSelector.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/package-info.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/reference/BuildCommits.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/reference/GitCheckoutListener.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/reference/GitCommitsCollector.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/reference/GitCommitsRecord.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/util/GitCommitTextDecorator.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/util/package-info.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/miner/GitMinerStepITest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/reference/GitCheckoutListenerITest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorderITest.java
- ui-tests/pom.xml
PR builds are already merged with master, so the merge commit needs to be removed.
Restructure the commit listener to record not only new commits but also the branching point.
> Add special handling for PR builds

- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/CommitStatisticsStep.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/reference/GitCheckoutListener.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/reference/GitCommitsRecord.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorder.java
Some code paths obtained the `GitCommitAction` from a build without checking the correct SCM ID. This may lead to errors when scanning for commits in the wrong SCM. 
See [JENKINS-66403](https://issues.jenkins.io/browse/JENKINS-66403).
> [JENKINS-66403] When obtaining the Git commits of a build always check the SCM key

- plugin/pom.xml
- plugin/src/main/java/io/jenkins/plugins/forensics/git/reference/GitCommitsRecord.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorder.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorderITest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorderTest.java
If the reference build detection does not work because the number of recorded commits is not large enough, then as a
fallback for pull requests the last build of the target branch will be returned as reference build.
> [JENKINS-66480] Add fallback reference build for multibranch projects.

- plugin/src/main/java/io/jenkins/plugins/forensics/git/util/GitCommitDecorator.java
Creation of commit links currently is done in the git-forensics plugin by accessing some internal API methods. It makes much more sense to move these methods to the git plugin itself. 
This PR depends on jenkinsci/git-plugin#1034 which has been released in [git-4.10.0](https://github.com/jenkinsci/git-plugin/releases/tag/git-4.10.0).
> Move repository browser commit link generation into git-plugin

- plugin/pom.xml
- plugin/src/main/java/io/jenkins/plugins/forensics/git/delta/DeltaRepositoryCallback.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/delta/GitDeltaCalculator.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/delta/GitDeltaCalculatorFactory.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/delta/model/GitDelta.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/delta/model/package-info.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/delta/package-info.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/delta/GitDeltaCalculatorFactoryTest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/delta/GitDeltaCalculatorITest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/delta/GitDeltaCalculatorTest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/delta/model/GitDeltaTest.java
- plugin/src/test/resources/design.puml
- ui-tests/pom.xml
I expanded the API from the Forensics API Plugin, which can be used for calculating the code difference between two commits, with a Git implementation.
The corresponding Draft Pull Request for the Forensics API Plugin can be found [here](https://github.com/jenkinsci/forensics-api-plugin/pull/372).
> Git implementation for delta API

- plugin/pom.xml
- plugin/src/main/java/io/jenkins/plugins/forensics/git/delta/GitDeltaCalculator.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/delta/GitDeltaCalculatorITest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/delta/GitDeltaCalculatorTest.java
- plugin/src/test/resources/design.puml
I implemented the new delta extension of the Forensics API Plugin for Git. The code delta can now be calculated between two Jenkins builds.
> Extended delta API

- plugin/pom.xml
- plugin/src/main/resources/io/jenkins/plugins/forensics/git/reference/GitCommitsRecord/summary.jelly
Symbols will automatically switch color based on the selected theme.
Followup to [jenkinsci/font-awsome-api#123](https://github.com/jenkinsci/font-awesome-api-plugin/pull/176)
> Replace icons with symbols

- plugin/src/main/java/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorder.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorderTest.java
Additionally, use permissions for a `BuildableItem` in all validations.
See https://issues.jenkins.io/browse/JENKINS-72317 for details.
> [JENKINS-72317] Use Jenkins.READ permission check for all list box models

- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/CommitAnalyzer.java
Create an empty change set when the commit cannot be resolved.
See [JENKINS-73524](https://issues.jenkins.io/browse/JENKINS-73524) for details
> [JENKINS-73524] When analyzing git results, log and ignore exceptions

- plugin/src/main/java/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorder.java
- plugin/src/main/resources/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorder/config.jelly
- plugin/src/main/resources/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorder/config.properties
- plugin/src/main/resources/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorder/help-considerRunningBuild.html
Downstream of https://github.com/jenkinsci/forensics-api-plugin/pull/557
> [JENKINS-73380] Add option to consider running builds as reference

- plugin/src/main/java/io/jenkins/plugins/forensics/git/delta/DeltaRepositoryCallback.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/delta/GitDeltaCalculator.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/delta/GitDeltaCalculatorITest.java
See [JENKINS-73297](https://issues.jenkins.io/browse/JENKINS-73297).
> [JENKINS-73297] Improve error handling when commit is not found

- plugin/pom.xml
- plugin/src/main/java/io/jenkins/plugins/forensics/git/blame/GitBlamer.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/delta/DeltaRepositoryCallback.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/delta/package-info.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/package-info.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/reference/package-info.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorderITest.java
> Use Java 17 and Jenkins 2.479.3 as baseline

- plugin/pom.xml
> Updating pom with latest forensic api plugin version

- plugin/pom.xml
Jenkins BOM contains all correct versions again.
> Use BOM versions for all dependencies marked with a TODO

- plugin/pom.xml
- plugin/src/test/java/io/jenkins/plugins/forensics/archunit/PluginArchitectureTest.java
Bump the version of plugin-util to 6.1165.v322e76215b_a_4. This version contains the missing class again.
> [JENKINS-76020] Resolve missing architecture rules
