jenkinsci/git-forensics-plugin

- Jenkinsfile
- pom.xml
- src/main/java/io/jenkins/plugins/forensics/git/blame/GitBlamer.java
- src/main/java/io/jenkins/plugins/forensics/git/miner/GitRepositoryMiner.java
- src/main/java/io/jenkins/plugins/forensics/git/util/AbstractRepositoryCallback.java
- src/test/java/io/jenkins/plugins/forensics/git/blame/GitBlamerITest.java
- src/test/java/io/jenkins/plugins/forensics/git/blame/GitBlamerTest.java
- src/test/java/io/jenkins/plugins/forensics/git/miner/GitRepositoryMinerITest.java
- src/test/java/io/jenkins/plugins/forensics/git/util/GitITest.java
See https://github.com/jenkinsci/analysis-model/pull/289
> Use relative path for all file operations

- ui-tests/main/java/io/jenkins/plugins/forensics/DetailsTable.java
- ui-tests/main/java/io/jenkins/plugins/forensics/DetailsTableRow.java
- ui-tests/main/java/io/jenkins/plugins/forensics/ScmForensics.java
- ui-tests/pom.xml
- ui-tests/test/java/io/jenkins/plugins/forensics/git/ForensicsPluginUiTest.java
Hallo Herr Hafner, 
ich habe im Table jetzt nicht die columns "Added" und "last commit" abgetestet, da sich diese ja stetig ändern und einen String, wie "7 days ago" oder "10 months ago" enthalten können. 
Für den Test nutze ich den Commit hash "28af63def44286729e3b19b03464d100fd1d0587", welcher einen Build des masters des forensics-plugins von vor 7 Tagen repräsentiert.
> Forensics plugin ui tests

- plugin/pom.xml
- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/CommitCollector.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/GitMinerFactory.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/GitRepositoryMiner.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/miner/GitMinerStepITest.java
Downstream for https://github.com/jenkinsci/forensics-api-plugin/pull/198
> [JENKINS_60931] Improve repository miner with an incremental analysis

- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/CommitCollector.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/GitRepositoryMiner.java
Fixed the order of commits for the FileDetailsView TrendChart.
> JENKINS-60935 Add churn metric - Fix for number of lines of code for moved or renamed files.

- package-lock.json
- plugin/pom.xml
- plugin/src/main/java/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorder.java
- plugin/src/main/resources/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorder/config.jelly
- plugin/src/main/resources/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorder/config.properties
- plugin/src/test/java/io/jenkins/plugins/forensics/git/PluginArchitectureTest.java
- Check for @POST
- Add permission checks
> Improve security for `doFill` methods

- plugin/pom.xml
- plugin/src/test/java/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorderITest.java
Use target branch "releases/warnings-2021" and feature branch "bugfixes/hotfix-124" when finding the reference build.
> Create an integration test that exposes JENKINS-64544

- ui-tests/pom.xml
> Bump JUT to 2.263.3 and run ATH tests with chrome-container

- plugin/pom.xml
- plugin/src/main/java/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorder.java
See [JENKINS-64627](https://issues.jenkins.io/browse/JENKINS-64627) for details.
> [JENKINS-64627] Use CONFIGURE permission of specific job if possible

- .github/workflows/ci.yml
- Jenkinsfile
- plugin/pom.xml
- plugin/src/main/java/io/jenkins/plugins/forensics/git/blame/GitBlamer.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/GitRepositoryMiner.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/util/GitCommitDecorator.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/blame/GitBlamerFactoryTest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/miner/GitMinerFactoryTest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/miner/GitMinerStepITest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/util/GitITest.java
- ui-tests/pom.xml
Requires new Jenkins Baseline 2.249.1
> Bump version of analysis-pom to to 5.0.0

- ui-tests/pom.xml
See https://www.jenkins.io/changelog-stable/#v2.277.1
> Set JUT baseline for UI tests to 2.277.1

- ui-tests/pom.xml
Use the latest LTS in UI tests.
> Bump version of Jenkins SUT to 2.289.3

- plugin/pom.xml
> Cleanup pom.xml versions

- ui-tests/pom.xml
> Bump Jenkins version for UI tests to 2.303.3

- plugin/src/main/java/io/jenkins/plugins/forensics/git/delta/GitDeltaCalculatorFactory.java
I added a missing extension annotation to the class `GitDeltaCalculatorFactory`.
> Added missing extension annotation

- plugin/pom.xml
- plugin/src/main/resources/index.jelly
- plugin/src/test/java/io/jenkins/plugins/forensics/git/PluginArchitectureTest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/blame/GitBlamerFactoryTest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/blame/GitBlamerITest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/blame/GitBlamerTest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/delta/GitDeltaCalculatorFactoryTest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/delta/GitDeltaCalculatorITest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/miner/CommitCollectorITest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/miner/DiffsCollectorITest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/miner/GitMinerFactoryTest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/miner/GitMinerStepITest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/miner/GitRepositoryMinerITest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/reference/GitCheckoutListenerITest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorderITest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/util/GitITest.java
Downstream PR of https://github.com/jenkinsci/plugin-util-api-plugin/pull/161.
> Use JUnit 5 for integration tests

- .github/workflows/ci.yml
- plugin/pom.xml
- ui-tests/pom.xml
Make plugin compatible with LTS releases 11 and 17.
> Let CI run with JDK 11 and 17

- ui-tests/pom.xml
- ui-tests/src/test/java/io/jenkins/plugins/forensics/git/SmokeTests.java
> Improve UI tests configuration

- plugin/pom.xml
- plugin/src/main/java/io/jenkins/plugins/forensics/git/blame/GitBlamer.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/delta/GitDeltaCalculator.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/delta/GitDeltaCalculatorFactory.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/util/GitCommitDecoratorFactory.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/PluginArchitectureTest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/delta/GitDeltaCalculatorFactoryTest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/delta/GitDeltaCalculatorITest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/delta/GitDeltaCalculatorTest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/delta/GitDeltaTest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/reference/GitMergeITest.java
> Add a field that stores the SCM for the delta calculator

- plugin/pom.xml
- plugin/src/main/java/io/jenkins/plugins/forensics/git/blame/GitBlamer.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/delta/DeltaRepositoryCallback.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/CommitStatisticsStep.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/GitRepositoryMiner.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/miner/RepositoryStatisticsCallback.java
- plugin/src/main/java/io/jenkins/plugins/forensics/git/util/GitRepositoryValidator.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/blame/GitBlamerITest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/blame/GitBlamerTest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/delta/GitDeltaCalculatorITest.java
- plugin/src/test/java/io/jenkins/plugins/forensics/git/reference/GitReferenceRecorderITest.java
Fix several new PMD warnings in PMD 7.x.
> Bump version of analysis-pom to 8.4.0

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/coverage.yml
- .github/workflows/quality-monitor.yml
> Enable quality monitor
